name: Build & Test

on:
  push:
    branches: [ master, production ]
  pull_request:
    branches: [ master, production ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          cache: true

      - name: Show .NET info
        run: dotnet --info

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: |
          dotnet test EconDataLens.Tests/EconDataLens.Tests.csproj \
          --configuration Release \
          --no-build \
          --logger "GitHubActions" \
          --logger "trx;LogFileName=test_results.trx"
